### ISSUE TITLE
The caret on the select component is the wrong colour

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#21]
**Describe the bug**
The downwards facing caret svg on the select component is blue. It should be black. 

**To Reproduce**
1. Go to 'https://neu-ui-docs.netlify.app/?path=/docs/form--input' and look at the select component 
2. Alternatively, download the package `import { Select } from 'ui-neu'`
3. Use the component. 

```
<FormGroup>
  <Label>Select</Label>
  <Select options={["egg", "milk", "bread"]}>Choose an option</Select>
</FormGroup>
```

**Expected behavior**
The caret is an inline svg. Used originally to improve cross browser compatibility of the custom select component. *Might be worthwhile double-checking that this is the best way to do things*. 

The caret should be black. It currently appears blue. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58988735/95656561-1fbba580-0b07-11eb-8ef6-789d9a8156d8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 85.0.x

**Comment by mojiwa** [comment]
Hi... mind if I take this one, please?

**Comment by daniel-norris** [comment]
Hey @mojiwa sure thing, I've assigned it to you 😊
