### ISSUE TITLE
Create list group component

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#26]
**Is your feature request related to a problem? Please describe.**
A user should be able to import and easily create and use list components in their project. 

**Describe the solution you'd like**
The user should be able to import list components from the package. The list component should enable the user to display `ul` and `li` items quickly and easily in their project, with a number of variants to choose from. The component's design should still try to keep in style with the rest of the library and neumorphic design (more info [here](https://www.figma.com/file/J1uPSOY5k577mDpSfGFven/Neomorphism-Guide-2.0-%7C-Original?node-id=26580%3A1425)) A common way to implement these types of components includes:

![image](https://user-images.githubusercontent.com/58988735/95677504-d5e1c680-0bbd-11eb-9de9-c2e4c9b25643.png)

**Describe alternatives you've considered**
Alternative implementations seen used by a lot of other popular React component libraries include: 

![image](https://user-images.githubusercontent.com/58988735/95677526-f447c200-0bbd-11eb-9c3c-8b0b0d2aa4a0.png)

![image](https://user-images.githubusercontent.com/58988735/95677535-03c70b00-0bbe-11eb-96fd-ae23cf9a304b.png)

![image](https://user-images.githubusercontent.com/58988735/95677537-0aee1900-0bbe-11eb-841b-67dcdea56f5d.png)

**Comment by sprakash57** [comment]
Shall I pick this up?

**Comment by daniel-norris** [comment]
Hey @sprakash57, that would be great! You're assigned.

**Comment by sprakash57** [comment]
@daniel-norris I have raised PR [https://github.com/daniel-norris/neu_ui/pull/88](https://github.com/daniel-norris/neu_ui/pull/88).
