### ISSUE TITLE
Create a nav component

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#27]
**Is your feature request related to a problem? Please describe.**
A user should be able to import and easily create a nav bar component from the package. 

**Describe the solution you'd like**
The user should be able to import a nav component from the package. The nav component should enable the user to create a nav, and its vertical or horizontal alignment. The style guide should include examples of how to include nav variants using other components available in the library. 

The component's design should still try to keep in style with the rest of the library and neumorphic design (more info [here](https://www.figma.com/file/J1uPSOY5k577mDpSfGFven/Neomorphism-Guide-2.0-%7C-Original?node-id=26580%3A1425)) A common way to implement these types of components includes:

![image](https://user-images.githubusercontent.com/58988735/95677593-73d59100-0bbe-11eb-97a3-c54c4c4edda8.png)

![image](https://user-images.githubusercontent.com/58988735/95677603-818b1680-0bbe-11eb-838c-0a491bf083cd.png)

![image](https://user-images.githubusercontent.com/58988735/95677608-894abb00-0bbe-11eb-8d6f-f4a89e2131fd.png)

![image](https://user-images.githubusercontent.com/58988735/95677610-910a5f80-0bbe-11eb-901e-45ffde1c27dd.png)

**Comment by veeralsharma** [comment]
can you assign me this

**Comment by daniel-norris** [comment]
Hey @veeralsharma sure thing. Thanks for helping to contribute, it's all yours 😊

**Comment by daniel-norris** [comment]
Hey @veeralsharma, I left you a message on your recent PR. Just wanted to check to see if you planned to come back to this issue or whether we should open it up to other contributors to have a go?

**Comment by veeralsharma** [comment]
i am very sorry there is some urgent work that came up ,, you can please
open the issue to everyone

**Comment by negiankit97** [comment]
@daniel-norris i'd like to work on this issue.

**Comment by daniel-norris** [comment]
Hey @negiankit97, thanks for offering to contribute. You're now assigned.
