### ISSUE TITLE
Missing semicolon in `src/components/buttons/Buttton.js `

### ISSUE THREAD

**Issue by petercr** [daniel-norris/neu_ui#36]
**Describe the bug**
So, **_it does not cause_** any breaking changes or anything, but there is a missing semicolon on line 14 of `Button.js`.
I can't _even really_ take credit for it, my linter caught it 🤷‍♂️ 

But I have a PR for the fix if you want, I just was not sure if you would rather have me make a PR or just fix it yourself. 

Either way just let me know here.

Thanks 😄 

`Rest of data excluded to save time`

**Comment by daniel-norris** [comment]
Oh go on then, @petercr 

You can submit the PR 🤣

**Comment by petercr** [comment]
Well here it is, the biggest most meaningful PR of **all time** 🤣 😆 
Okay fine, it's just a semicolon 👌 

Hopefully my next PR will actually _do something_ 😂 
Thanks
