### ISSUE TITLE
Create a simple test for the CardHeader component

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#40]
**Is your feature request related to a problem? Please describe.**
Test coverage across the application is low. We need to build confidence that the components have the expected behaviour that we want and to help mitigate any regression in the future. 

**Describe the solution you'd like**
We need to implement better test coverage across the library. Ideally each component should be accompanied by a test case written using Jest. At a minimum the test should check whether the component successfully shows any child `props`.

We should have a test case covering the CardHeader component implemented using Jest. More info on Jest can be found [here](https://jestjs.io/).

For examples of how this is done, take a look at existing test cases in the library. An example would be the typography or button components. 

This is part of epic #19.

**Comment by jscastanos** [comment]
Hi, I'd like to work on this issue.

**Comment by daniel-norris** [comment]
Hey @jscastanos, thanks for offering to contribute. You're now assigned.
