### ISSUE TITLE
Create a simple test for the Input component 

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#41]
**Is your feature request related to a problem? Please describe.**
Test coverage across the application is low. We need to build confidence that the components have the expected behaviour that we want and to help mitigate any regression in the future. 

**Describe the solution you'd like**
We need to implement better test coverage across the library. Ideally each component should be accompanied by a test case written using Jest. At a minimum the test should check whether the component successfully shows any child `props`.

We should have a test case covering the Input component implemented using Jest. More info on Jest can be found [here](https://jestjs.io/).

For examples of how this is done, take a look at existing test cases in the library. An example would be the typography or button components. 

This is part of epic #19.

**Comment by momosetti** [comment]
Could i work on it?

**Comment by daniel-norris** [comment]
Sounds good @momosetti, it's all yours.

**Comment by momosetti** [comment]
Hi @daniel-norris , i made a PR at #51, could you check it, waiting for your feedbacks.
