### ISSUE TITLE
Add Translations Links to Original README

### ISSUE THREAD

**Issue by s0meon3** [daniel-norris/neu_ui#42]
I've noticed that the README in english doesn't link to the already translated ones, and I think it would be a good idea to add a link to each translated README.

Btw, I would like to work on it too, since it's a really small change.

**Comment by daniel-norris** [comment]
Sounds like a great idea @s0meon3!

**Comment by s0meon3** [comment]
Great! I'll start working on it tonight :)

**Comment by daniel-norris** [comment]
Could you also leave a star on the repository please? Let's get it to 10 x 💛

**Comment by s0meon3** [comment]
Sure! This repo is awesome!
