### ISSUE TITLE
Radio buttons are not behaving as expected on mobile

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#44]
**Describe the bug**
The radio component does not appear correct on a mobile Android device. Have not attempted to replicate on iOS. Appears fine on desktop. 

**To Reproduce**
1. Go https://neu-ui-docs.netlify.app/?path=/docs/form--input on a mobile Android device 

**Expected behavior**
The "bullet points" should be aligned instead of out of place like they appear at the moment. 

**Screenshots**
![Screenshot_20201016-170356_Chrome.jpg](https://user-images.githubusercontent.com/58988735/96282208-50ea1900-0fd2-11eb-9f88-ff8e36e399e5.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 9+
 - OS: Android 8.0.0.

**Additional context**

**Comment by sprakash57** [comment]
I would like to work on this issue.

**Comment by daniel-norris** [comment]
Sure, thanks for offering to contribute @sprakash57. You're now assigned.

**Comment by sprakash57** [comment]
@daniel-norris need some help. Does the below change look good? Let me know if it fulfills the requirement.
![image](https://user-images.githubusercontent.com/38065786/96281194-a1736d80-0ff6-11eb-8d20-d8d6b2cc2247.png)

Before changes, it was looking like this on mobile -
![image](https://user-images.githubusercontent.com/38065786/96281040-68d39400-0ff6-11eb-86a9-d8adefbdead9.png)

One more thing I have noticed that the Radio component rendered twice in the story. Do you want me to fix that as well?

**Comment by daniel-norris** [comment]
Hey @sprakash57 this is what I'm getting currently on production on Android..

![Screenshot_20201016-170356_Chrome.jpg](https://user-images.githubusercontent.com/58988735/96281765-b5f13f00-0fd1-11eb-8d68-41644b220241.jpg)

I wonder if this may be something to do with Storybook 🤔.

**Comment by sprakash57** [comment]
Actually, chrome was not updated on my phone. I have updated it and now I am able to replicate the issue. i will keep you posted.

**Comment by sprakash57** [comment]
@daniel-norris I have fixed the issue. Here is what I have done. 
- Detected userAgent (Whether it's mobile or desktop browser) 
- Applied CSS into styled-components as per userAgent.

Total lines of codes modified/added - 3

Final results -
1. Mobile 
![image](https://user-images.githubusercontent.com/38065786/96295940-1c934e80-100c-11eb-8b6a-4e60b88bd152.png)
2. Desktop
![image](https://user-images.githubusercontent.com/38065786/96296015-392f8680-100c-11eb-8cf6-f20659867b41.png)

**Comment by sprakash57** [comment]
Raised [https://github.com/daniel-norris/neu_ui/pull/47](https://github.com/daniel-norris/neu_ui/pull/47) for review.
