### ISSUE TITLE
Refactor the Toggle component

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#5]
The existing toggle.js component needs to be refactored so that it uses the input[type=checkbox] element.

**Comment by phanlyhuynh** [comment]
Hi. Can you assign to me? Thanks!!!

**Comment by daniel-norris** [comment]
Hey @phanlyhuynh sure thing :)

**Comment by daniel-norris** [comment]
Hey @phanlyhuynh are you still planning on working this issue or can we open it back up again to other contributors?

**Comment by phanlyhuynh** [comment]
@daniel-norris Yes. you can open and assign to other contributors. Thanks

**Comment by mankal111** [comment]
I would like to do it
