### ISSUE TITLE
Create a CardText test

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#56]
**Is your feature request related to a problem? Please describe.**
Test coverage across the application is low. We need to build confidence that the components have the expected behaviour that we want and to help mitigate any regression in the future.

**Describe the solution you'd like**
We need to implement better test coverage across the library. Ideally each component should be accompanied by a test case written using Jest. At a minimum the test should check whether the component successfully shows any child props. If you are able to include tests for any additional functionality then that would be appreciated!

We should have a test case covering the CardText component implemented using Jest. More info on Jest can be found here.

For examples of how this is done, take a look at existing test cases in the library. An example would be the CardHeader or Input components.

You can run your tests using `npm run test` or to see test coverage across the library `npm run test:cov`.

This is part of epic #19.

**Comment by momosetti** [comment]
I will fix this one @daniel-norris .

**Comment by daniel-norris** [comment]
Great, you're assigned @momosetti
