### ISSUE TITLE
Improve Typography component test to 100% coverage

### ISSUE THREAD

**Issue by daniel-norris** [daniel-norris/neu_ui#72]
**Is your feature request related to a problem? Please describe.**
Test coverage across the application is low. We need to build confidence that the components have the expected behaviour that we want and to help mitigate any regression in the future.

**Describe the solution you'd like**
We need to implement better test coverage across the library. Ideally each component should be accompanied by a test case written using Jest.

We need to improve the test coverage for the Typography component, currently implemented using Jest, to 100% coverage of the component. It currently stands at ~45%. More info on Jest can be found here (https://jestjs.io/). 

![image](https://user-images.githubusercontent.com/58988735/96526095-8f9efe00-1274-11eb-97ab-d1c61d377053.png)

For examples of how this is done, take a look at existing test cases in the library. An example would be the CardHeader or Input components.

You can run your tests using npm run test or to see test coverage across the library npm run test:cov.

This is part of epic #19.

**Comment by greyGroot** [comment]
@daniel-norris please, assign this one to me, i want to do it.

**Comment by daniel-norris** [comment]
Hey @greyGroot, thanks for wanting to help out but it looks like someone has beaten you to a PR submission on this one. Feel free to pick something else out or alternatively suggest an issue and PR yourself.
