### ISSUE TITLE
Button change cursor onhover

### ISSUE THREAD

**Issue by greyGroot** [daniel-norris/neu_ui#87]
**Describe the bug**
When cursor is hovered over button, it's not changed.

**To Reproduce**
hover cursor over button

**Expected behavior**
Cursor should be changed.

**Screenshots**
<img width="1440" alt="Screenshot 2020-10-20 at 20 06 40" src="https://user-images.githubusercontent.com/41450089/96620400-0dfcae00-1310-11eb-9e31-81b35a4eabbd.png">

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Chome
 - Version 86.0.4240.80 (Official Build) (x86_64)

**Comment by greyGroot** [comment]
@daniel-norris i wold like to do it, could you assign it to me?

**Comment by daniel-norris** [comment]
Great idea @greyGroot, you're assigned.
